/*
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Answer : 4613732
*/

/*
TIPS :
Looking at the series :
1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233....
      ^        ^           ^            ^

Recurrence for Even Fibonacci sequence is:
EFn = 4EFn-1 + EFn-2

with seed values
EF0 = 0 and EF1 = 2.

EFn represents n'th term in Even Fibonacci sequence.
*/

#include<iostream>

using namespace std;

int main(){
	
	int n = 4000000;
	long long int ef1 = 0, ef2 = 2;
	long long int sum = ef1 + ef2;
	
	if(n<2){
		return 0;
	}
	
	while(ef2<n){
		long long int ef3 = 4*ef2 + ef1;
		
		if(ef3>n){
			break;
		}
		
		ef1 = ef2;
		ef2 = ef3;
		sum+=ef2;
	}
	
	cout<<sum<<endl;

	return 0;
}
